- Analyze the central tendency and distribution measurements with the mathematical formula given above and the built-in codes available in python through 3 different data that you will generate using the numpy library !!!

In [5]:
import numpy as np
import pandas as pd

df = pd.DataFrame()
df['data1'] = [28, 42, 27, 24, 35, 54, 35, 37]
data2 = np.random.normal(69,8,100)
data3 = np.random.normal(64,5,100)

sum(df['data1']) / len(df['data1'])
sum(data2)/len(data2)
y=sum(data3)/len(data3)

print("mean data1:  " ,np.mean(df['data1']))
print("mean data2:  " ,np.mean(data2))
print("mean data3:  " ,y)


mean data1:   35.25
mean data2:   67.47733719906098
mean data3:   64.23410868663747


In [23]:
import statistics
print("median data1: ",statistics.median(df['data1']))
print("median data2: ",np.median(data2))
print("median data3: ",np.median(data3))
print(df['data1'].describe())
print(df['data1'].median())

median data1:  35.0
median data2:  67.48603053721044
median data3:  64.14584724161406
count     8.000000
mean     35.250000
std       9.617692
min      24.000000
25%      27.750000
50%      35.000000
75%      38.250000
max      54.000000
Name: data1, dtype: float64
35.0


In [52]:
print(statistics.mode(df['data1']))
print(statistics.mode(data2))
print(statistics.mode(data3))

35
66.99106475157815
66.48576561017863


In [59]:
print(np.unique(df['data1']))
np.unique(data2)

[24 27 28 35 37 42 54]


array([51.86581529, 52.91135746, 54.6515194 , 54.95608019, 54.98394479,
       55.38278883, 56.05256966, 56.2623831 , 56.3018133 , 56.42339087,
       56.48217051, 56.83987595, 58.01332477, 58.11050358, 58.53431067,
       59.15147827, 59.37873439, 59.59066142, 59.63122789, 59.745348  ,
       59.85017671, 59.8905205 , 59.89541285, 59.98734009, 60.3304071 ,
       60.99009444, 61.68948934, 61.95279137, 61.98954373, 62.51682398,
       62.58077766, 63.00400392, 63.3469395 , 63.57422656, 64.06037387,
       64.2774356 , 64.38572733, 64.99800792, 65.15910045, 65.18768144,
       65.59597593, 65.60281177, 66.10253591, 66.21338155, 66.58254511,
       66.70170621, 66.72043535, 66.91974768, 66.99106475, 67.48380759,
       67.48825349, 67.54111698, 68.34581633, 68.34603368, 68.42375166,
       68.52460364, 68.95277339, 69.03392474, 69.25483953, 69.29246913,
       69.34318892, 69.45004348, 69.62050208, 69.71433622, 69.98607522,
       70.11995135, 70.91723346, 71.01077336, 71.13894362, 71.57

In [42]:
np.unique(df['data1'])
(values, counts) = np.unique(df['data1'],return_counts=True)
ind=np.argmax(counts)
values[ind]

35

In [40]:
print(np.unique(df['data1'],return_counts=True))
print(np.argmax(counts),"index has a maximum value")

(array([24, 27, 28, 35, 37, 42, 54]), array([1, 1, 1, 2, 1, 1, 1]))
3 index has a maximum value


distribution measurements

In [98]:
print("variance data1: ",np.var(df['data1'],ddof=1))
print("variance data2: ",np.var(data2))
print("variance data3: ",np.var(data3))

variance data1:  92.5
variance data2:  63.87608915744011
variance data3:  25.796030161091767


In [91]:
print("std dev data1: ",np.std(df['data1'],ddof=1)) #numpy
print("std dev data2: ",data2.std()) #pandas
print("std dev data3: ",data3.std())

std dev data1:  9.617692030835672
std dev data2:  7.9922518201968655
std dev data3:  5.078979244010726


In [100]:
print("standard error data1: ",np.std(df['data1'] ,ddof=1) / np.sqrt(len(df['data1'])))
print("standard error data2: ",data2.std()/np.sqrt(len(data2)))
print("standard error data3: ",data3.std()/np.sqrt(len(data3)))

standard error data1:  3.4003676271838605
standard error data2:  0.7992251820196865
standard error data3:  0.5078979244010726
